- hosts: fw1
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: no
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 80
  tasks:
  
  - name: Backup a virtual domain.
    fortios_monitor_fact:
      selector: 'system_config_backup'
      vdom: 'root'
      params:
          scope: 'global'
    register: backupinfo

  - name: Save the backup information.
    copy:
      content: '{{ backupinfo.meta.raw }}'
      dest: './local.backup'