---
- hosts: localhost
  collections:
  - fortinet.fortios
  vars:
   host: "172.16.10.11"
   username: "turing"
   password: ""
   vdom: "root"
   ssl_verify: "False"
  tasks:
  - name: Configure IPv4 addresses.
    fortios_firewall_address:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "True"
      ssl_verify:  "{{ ssl_verify }}"
      state: "present"
      firewall_address:
        allow_routing: "disable"
        comment: "Comment."
        name: "test_test"
        subnet: "1.1.1.0 255.255.255.0"
        type: "ipmask"
